### ISSUE TITLE
Doesn't work on Windows!

### ISSUE THREAD

**Issue by franciscop** [franciscop/server#10]
For some reason the files served with the static middleware don't load on Windows.

1. Find the bug (check absolute paths and `C://` issues).
1. Fix the bug.
1. Establish a testing methodology that involves windows as well.

**Comment by Jackbennett** [comment]
This used to work fine FYI my PRs came from windows. I'm not sure exactly when it broke I've been off coding for a little while.

**Comment by franciscop** [comment]
I am pretty sure I broke it :(

The problem is two-fold:

- It cannot find the correct path for the files (main problem).
- The request never ends as there's nothing to catch it nor to show the error. This should probably be handled on the final callback.

I am going to get a Windows machine ASAP, this should be fixed for next week (I'm doing a workshop).

**Comment by Jackbennett** [comment]
You can get free windows VM's for browser testing by the way; https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by franciscop** [comment]
@Jackbennett but that seems to be for Microsoft Edge testing, right? I would need a full windows machine to install Node.js, server and test it in whatever browser; the problem is in the back-end, not in the front-end.

**Comment by Jackbennett** [comment]
Correct but it's just a windows VM for legitimate licensing for testing. I'm like 99% positive you can use that, load node, chrome and FF onto it, snapshot it and test all you like. Ignore that browserstack stuff you're right that's only front end.

**Comment by franciscop** [comment]
I got it failing in a Windows CI so tests will be run automatically, and it seems like the static one is the only test failing (though not everything is tested): https://ci.appveyor.com/project/franciscop/server

I will look into into the link you sent, a CI is not a good place to debug things.

**Comment by franciscop** [comment]
Okay, the issue [seems to come](https://ci.appveyor.com/project/franciscop/server/build/15) from environment variables. In windows there's apparently an environment variable called "public" (case insensitive), which points to `C:\\Users\\Public` and messes with all successful things.

I am waiting for confirmation on this with a real windows system instead of the CI.
