### ISSUE TITLE
Access route parameters in Pug

### ISSUE THREAD

**Issue by karneaud** [franciscop/server#101]
I have a route as follows

```
get('/player/:id', ctx => { render('player', { user: id })})
```

where **id** is the route's parameter. how is the data instantiated in the render function for the view?

**Comment by franciscop** [comment]
You need to extract it from `ctx.params.id` like:

```js
get('/player/:id', ctx => { render('player', { user: ctx.params.id })})
```

See these docs:

https://serverjs.io/documentation/context/#-params
