### ISSUE TITLE
oauth2 POST  to external site

### ISSUE THREAD

**Issue by Astrydax** [franciscop/server#104]
**What are you trying to do?**
I'm trying to implement windows live authentication. The only reason I need this is to validate users gamertags they use on XBL. To do this I need to send a post request to an external site. I can't find functionality on how to do this with server.js

**Comment by franciscop** [comment]
I am sorry but Server is not made to send external requests, only to receive requests as servers normally do. You might want to look into the packages `got`, `request`, etc.
