### ISSUE TITLE
Support HEAD request method

### ISSUE THREAD

**Issue by justinpage** [franciscop/server#109]
**What are you trying to do?**
We use New Relic for monitoring our applications. I noticed that HEAD request to our application fails. What is the easiest path in supporting HEAD request. My understanding is that express supports HEAD by means of GET but maybe with this package, we have to be more explicit

**Ask your question**
How do we support HEAD request to the root of our application. Do we simply add logic to one of our middlewares to check if the method request is HEAD:

```
ctx.method.toLowerCase() === 'head' ? 200 : false
```

Returning 200 when request method is HEAD otherwise false which would move on to other middleware. 

Wanted to double check if this was the easiest solution to this problem.

**Comment by franciscop** [comment]
That sounds about right [from the source code](https://github.com/franciscop/server/blob/master/src/join/index.js#L7) 👌

Please let me know if you have any issues with this, I'll leave it open for a couple of days
