### ISSUE TITLE
Response/Reply

### ISSUE THREAD

**Issue by franciscop** [franciscop/server#11]
Find a decent way to handle the responses for the beta, even though it won't be properly documented in the alpha there should be a canonical example. There are three main options and then combinations of them:

## A bit of magic

```js
server(ctx => 'Hello 世界');
server(ctx => render('index.pug'));
server(ctx => 404);
server(ctx => ['I', 'am', 'a', 'json']);
server(ctx => { I: 'am', also: 'a json' });
```

Pros:

- Conceptually really nice
- Follows somewhat Koa
- Simple and clear
- Final+error simple to check

Cons:

- It still needs some contextual extra methods such as render(), sendFile(), etc.
- Combining them is awkward; this should be combined with one of the options below.

## Explicit external

The methods are part of a global and should be returned:

```js
const { send, json, render, status } = server.reply;

server(ctx => send('Hello 世界'));
server(ctx => render('index.pug'));
server(ctx => status(404));
server(ctx => json(['I', 'am', 'a', 'json']));
server(ctx => json({ I: 'am', also: 'a json' }));
```

Pros:

- Consistent
- Explicit
- Return == send analogy still works

Cons:

- Hidden dependency; the function *has* to be returned.
- Final+error become unreliable if the hidden dependency is broken.

## Explicit internal

Everything is within the context. Work around the verb "send" to avoid changing/using `res` (as res uses callbacks which mess up everything):

```js
server(ctx => ctx.send('Hello 世界'));
server(ctx => ctx.send.render('index.pug'));
server(ctx => ctx.send.status(404));
server(ctx => ctx.send.json(['I', 'am', 'a', 'json']));
server(ctx => ctx.send.json({ I: 'am', also: 'a json' }));
```

Pros:

- Really explicit and clear what it does.

Cons:

- Way too verbose, becomes annoying after a while.

## Alternatives

Keep a bit of magic + explicit external or internal for the complex cases.

Return an object = response (instead of JSON). Example: `{ body: 'whatever', status: 200 }`

Return an instance of a class = response (such as Reply). Example: status(200).send('whatever');

**Comment by jxub** [comment]
Explicit external looks like the optimum approach to me, speaking as a newb.js from a purely estetical perspective

**Comment by franciscop** [comment]
On a second thought I'll leave this open until [all the methods are implemented](https://github.com/franciscop/server/blob/master/src/reply/index.js).
