### ISSUE TITLE
How to use morgan on server?

### ISSUE THREAD

**Issue by LucasMonteiro1** [franciscop/server#113]
I tried 

```js
server(options, routes).then((ctx) => {
  ctx.app.use(morgan('tiny'));
});
```
and
```js
server(options, routes, morgan);
```
and
```js
server(options, routes, morgan('tiny'));
```

After installing the morgan dependency, I changed the file `server/plugins/express/index.js`, after the line `ctx.app = ctx.express();` added `ctx.app.use(morgan('tiny'));` and it worked.

**Comment by franciscop** [comment]
Have a look at [Express Middleware](https://serverjs.io/documentation/#express-middleware), have you tried something like this?

```js
const server = require('server');

// Convert an Express to a Server middleware
const morgan = server.utils.modern(require('morgan')({ ... }));

// Add it as you'd add a normal middleware
server({}, morgan, ...);
```

**Comment by LucasMonteiro1** [comment]
It worked using the middleware. Thank you for your help!!

**Comment by franciscop** [comment]
Happy to help :)
