### ISSUE TITLE
How to use anything other than auth0?

### ISSUE THREAD

**Issue by elieobeid7** [franciscop/server#116]
I don't like the idea for paying for something as silly as authentication, especially when one could implement passportjs or firebase authentication in seconds. Therefore I don't want to use auth0, how to change it?

**Comment by franciscop** [comment]
There's nothing about Auth0 integrated, they were gonna sponsor at some point so I added their logo, but the conversation died in the end.

**Comment by sw-yx** [comment]
"implement passportjs in seconds" come on... have you tried implementing passportjs well? lol

**Comment by elieobeid7** [comment]
Why would I want to even implement passport if I could implement firebase? It was just an example on top of my head, why pay for db when firebase is free and even better than passport.

**Comment by sw-yx** [comment]
https://finance.yahoo.com/quote/OKTA/

**Comment by elieobeid7** [comment]
https://finance.yahoo.com/quote/OKe
