### ISSUE TITLE
How to configure socket.io?

### ISSUE THREAD

**Issue by jazzyjeff5** [franciscop/server#123]
Sorry if this is explained in the documentation, I couldn't find it.
ServerJS uses socket.io to handle websockets, right?

I need to configure maxHttpBufferSize to limit huge messages from being sent to my server, see:

https://socket.io/docs/server-api/

How do I set this parameter through ServerJS? Thanks!

**Comment by franciscop** [comment]
Woah, that seems to be not documented at all! Thanks for the issue.

socket.io is [implemented as a plugin](https://github.com/franciscop/server/blob/master/plugins/socket/index.js), which means that you might think this would work:

```js
// Ideal, but does not work now
const options = {
  socket: { ... }
};
server(options, middleware);
```

Unfortunately options are not passed to the socket.io constructor currently:

```js
// plugins/socket/index.js
ctx.io = socketIO(ctx.server);  // No options
```

Let me try to fix this

**Comment by franciscop** [comment]
It should be fixed now if you upgrade to the latest `server` 🎉

Could you please try it and let me know? [See the example](https://github.com/franciscop/server/blob/master/examples/websocket/index.js) for some reference.

**Comment by jazzyjeff5** [comment]
Works, thank you very much :D

**Comment by franciscop** [comment]
So happy to hear 🎉

Please let me know if you find any other issue. I'll leave this open until I can document the option later

**Comment by franciscop** [comment]
Added some basic docs to the website:

[**Socket Options**](https://serverjs.io/documentation/options/#socket)

Please feel free to improve them! Documentation for this is here:

[**Options documentation**](https://github.com/franciscop/server/blob/master/docs/documentation/options/README.md)

What value did you end up using for `maxHttpBufferSize`? That sounds like a good example for the docs.
