### ISSUE TITLE
React plugin

### ISSUE THREAD

**Issue by franciscop** [franciscop/server#13]
EDIT: rethought the plugin system. Install an official plugin (those with the `@server/` prefix):

```
npm install @server/react
```

Then just use it. Any installed official package will be automatically required by server, so no need to write specific code for importing it. Then just use it however its documentation describes:

```js
// index.js
const server = require('server');
const { render } = server.reply;

server(ctx => render('app.jsx', { user: 'Francisco' }));
```

Then we would be able to have in our `app.jsx`, reading explicit and implicit variables:

```js
// app.jsx
import react from 'react';

export default (props) => (
  <div>
    <h1>Welcome {props.user}</h1>
    <p>server.js is so cool! You are reading {props.path}</p>
  </div>
);
```

Inspired by [Next.js](https://zeit.co/blog/next2) and checked feasibility with [Paypal's react-engine](https://github.com/paypal/react-engine) and [React.js' express-react-views](https://github.com/reactjs/express-react-views).

**Comment by grantlouisherman** [comment]
Hey francis, would you mind if I took a crack at this?

**Comment by franciscop** [comment]
Hi @grantlouisherman the Plugins API is undocumented and it *will* change so **I would recommend not doing this plugin at this point**. For instance, [the options will be a large breaking change](https://github.com/franciscop/server/issues/14) from what is being done right now.

There is no estimated timeline for the 1.1, now I'm wrapping up the beta 2 for the 1.0 and there will be also a beta 3 so it'll be at least few months. This plugin is also really complex, so please explain what you intend on doing before having a go at it. The basic plugin interface so far is:

```js
module.exports = {
  name: 'react',
  options: {
    // ...
  },
  init: [middleware that executes once on startup (no req/res data available)],
  before: [middleware that executes before user middleware],
  after:  [middleware that executes after user middleware],
  launch: [middleware that executes once the server is running (no req/res data available]
};
```

Then to add it the only way so far is this:

```js
const server = require('server');
const react = require('server-plugin-react');

server.plugins.push(react);

server();
```

Suggestions (but when doing it you will get a better view of the limitations of those):

- You'll need some basic HTML template where the components will be rendered.
- Keep it to `0.x` versions until there is a stable plugin API and until the plugin itself is stable.
- When `ctx.options.env !== 'development'`, execute the bundling inside the `init()` and just use this bundle later on. On development, run it **also** on `before()` to allow real time changes. This might not be needed though, depending on which engine you use.

**Conclusion**: if you really want/need it at this point or don't mind the really unstable state, go ahead. However I do not recommend doing it at this point. If you have any question feel free to ask, and please tell me how you plan on doing it.

**Comment by franciscop** [comment]
Done in https://github.com/franciscop/server-react
