### ISSUE TITLE
How integrat ApolloGraphql use serverjs

### ISSUE THREAD

**Issue by ngocdtph03070** [franciscop/server#137]
Hi you. Can I integrate ApolloGraphql use project?

**Comment by franciscop** [comment]
Yes.

That said, this is an Issue tracker not a forum nor a chat. Please have a look at https://www.apollographql.com/docs/apollo-server/ and if you find any specific issue in Server.js feel free to open an Issue explaining the issue and showing the code. You can also use the [Discussions](https://github.com/franciscop/server/discussions) for more general questions, but still should be Server.js oriented and with specific questions.
