### ISSUE TITLE
Any schedule for migrating to socket.io 4.x?

### ISSUE THREAD

**Issue by lantica** [franciscop/server#139]
The socket.io using now is v 2.x, which means client using v3.x / 4.x will not be able to connect.
I would like to know is there any plan for updating it?

**Comment by franciscop** [comment]
Sorry no plans at the moment for that, do versions 3.x and 4.x totally break backwards compatibility?

**Comment by lantica** [comment]
Yes, there is backward compatibility for both v3.x and v4.x server to v2.x client.
However, an option (`allowEIO3: true`) will be required in order for the backward compatibility.

**Comment by kinostl** [comment]
#144 updated this to 4.5

**Comment by franciscop** [comment]
Thanks! I guess we can close this now :)

**Comment by franciscop** [comment]
Note: not released yet, will be released within a couple of days
