### ISSUE TITLE
Heroku wrong IP

### ISSUE THREAD

**Issue by franciscop** [franciscop/server#140]
**Describe the bug**
The described way of obtaining the IP is through `ctx.ip`, but in Heroku (and possibly others) this is returning an internal IP, and not the user IP as expected. Instead, server.js should use [`ctx.headers["x-forwarded-for"]`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For) to correctly find the IP when possible, since it's a "de-facto standard".

**To Reproduce**
1. Log the IP `console.log(ctx.ip)`
2. Deploy on Heroku
3. Check the IP in the logs (it's local)
4. Google "What is my IP" and see that ofc it's different

**Expected behavior**
The result from What is my IP and Heroku logs' IP should be the same

**Possible Fix**
A potential fix:

```js
export default forwardedMiddleware = ctx => {
  const forwarded = ctx.headers["x-forwarded-for"];
  if (forwarded) {
    ctx.ip = forwarded.trim().split(/\,\s?/g).shift();
  }
}
```

**Comment by franciscop** [comment]
Fixed 👍

**Comment by SidneyNemzer** [comment]
Note that clients can also set the header, potentially allowing clients to spoof their IP.

By default, Express ignores the header, but the server can opt-in to parse it using `app.set('trust proxy')`. [(docs)](https://expressjs.com/en/4x/api.html#app.settings.table)
