### ISSUE TITLE
Update formidable

### ISSUE THREAD

**Issue by kinostl** [franciscop/server#146]
**Is your feature request related to a problem? Please describe.**
NPM Recommends updating formidable to v2 or v3.

**Describe the solution you'd like**
Update formidable. Going for v3 might be a good idea.

**Additional context**
`npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau`

**Comment by franciscop** [comment]
I updated formidable by using [upload-files-express](https://www.npmjs.com/package/upload-files-express), thanks for the bug request! 👍
