### ISSUE TITLE
while trying post method throwing invalid csrfToken  error - how to resolve this

### ISSUE THREAD

**Issue by seelasudheer99** [franciscop/server#151]
**i am trying the post method**

post('/exportLots', async (ctx) => {
    console.log('ctx', ctx)
  }),

the above snippet is in server.js - react js application

get is working fine, for post its throwing error -  invalid csrf token

**so how to add csrf token ? **

**Environment (optional):**
 - Reactjs :
 - Node.js:
 - Server.js:

**Additional context (optional)**

**Comment by franciscop** [comment]
See the [CSRF token](https://serverjs.io/documentation/router/#csrf-token) guide:

For POST, PUT and DELETE requests a valid [CSRF token](https://github.com/expressjs/csurf) with the field name of _csrf must be sent as well. The local variable is set by server.js so you can include it like this:

```html
<form action="/" method="POST">
  <input name="firstname">
  <input type="submit" value="Contact us">
  <input type="hidden" name="_csrf" value="{{csrf}}">
</form>
```

If you are using an API from Javascript, such as the new fetch() you can handle it this way:

```js
<!-- within your main template -->
<script>
  window.csrf = '{{csrf}}';
</script>

// Within your javascript.js/bundle.js/app.js
fetch('/', {
  method: 'POST',
  body: 'hello world',
  credentials: 'include',  // Important! to maintain the session
  headers: { 'csrf-token': csrf }  // From 'window'
}).then(...);
```

Or you could also just disable it if you know what you are doing:

```js
server({ security: { csrf: false } }, ...);
```

**Comment by franciscop** [comment]
For extra context (heh) for APIs, the CSRF token is in your context as `ctx.csrf` so you can pass it along e.g. on login:

```js
get('/login', ctx => {
  // Do your logic

  return {
    user,
    csrf: ctx.csrf
  };
});
```
