### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by bigtunacan** [franciscop/server#21]
What is the preferred way to enable CORS using this framework?

**Comment by franciscop** [comment]
[Following this express example](https://enable-cors.org/server_expressjs.html):

```js
const { header } = require('server/reply');  // OR server.reply;

const cors = [
  ctx => header("Access-Control-Allow-Origin", "*"),
  ctx => header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept")
];

server({}, cors, ...);
```

Cannot test it right now though, if you try it and it works please let me know!

**Comment by franciscop** [comment]
[Alternatively](https://stackoverflow.com/a/21622564/938236), with the [cors package](https://npmjs.org/package/cors):

```js
const cors = require('cors');

server({},
  server.utils.modern(cors()),
  ...
);
```

**Comment by franciscop** [comment]
From the amount of likes it seems like cors package works properly. The code I pasted manually also seems to be setting the headers properly, so I'll close this as fixed.
