### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by frenchbread** [franciscop/server#22]
Hello,

Are there any approaches for authentication implemented yet? For example, something like `passport-jwt` would be nice to have.

Thanks.

**Comment by franciscop** [comment]
There is officially nothing. I want to experiment around for the plugins in 1.1 as I want to make an official `auth` plugin, but even the plugin specs is far away from being stable so don't expect it soon.

That being said, [`passport`](http://www.passportjs.org/) should work. Server accepts its own version of middleware by default, but if [you wrap it as explained here](https://serverjs.io/documentation/#express-middleware) you can use express middleware like passport.

**Comment by frenchbread** [comment]
Yep, it works. Created [server.js-auth-example](https://github.com/frenchbread/server.js-auth-example) that uses JWT for authentication.
