### ISSUE TITLE
Found a problem with the env.js parsing

### ISSUE THREAD

**Issue by CycoPH** [franciscop/server#24]
On my machine (win 10, latest node) I have an environment variable that looks like this:
ConEmuArgs2=-cmdlist {cmd} -cur_console:n

The is.json test fails on this.
I think you should never do a JSON.parse outside a try catch

A simple fix is this:

```js
const type = str => {
  if (!str) return;
  if (typeof str !== 'string') return str;
  if (is.numeric(str)) return +str;
  if (is.boolean(str)) return /true/i.test(str);
  if (is.json(str)) {
    try {
      return JSON.parse(str);
    }
    catch(e) {

    }
  }
  return str;
};
```

**Comment by franciscop** [comment]
You are totally right, this is a big mistake. `JSON.parse()` should always be within a try/catch. I will get this fixed today.
