### ISSUE TITLE
Clarify logging functionality

### ISSUE THREAD

**Issue by klemola** [franciscop/server#25]
Hi,

I've been testing various features of `server` today, and logging functionality puzzles me. If I just set log level via either `.env` file or via options on startup, `ctx.log.info('foo')` doesn't write anything to STDOUT.  I can produce STDOUT output by using the stream directly (`ctx.log.stream.write('foo')`). Normal `console.log` works as expected.

Is there a log file somewhere? How can I log into STDOUT / STDERR using `ctx.log`?

Thanks in advance!

Matias

-------------------------------
`server` version: `1.0.1`
`node` version: `8.9.0`
Platform: macOS Sierra
Terminal: iTerm 2 `build 3.1.4`

**Comment by franciscop** [comment]
There was a bug introduced at some point. Should be fixed now, the reason it was not caught is because of the difficulty to test this.

**Comment by franciscop** [comment]
I have added a couple of examples in the docs and one in the `examples/log`, but basically you were doing it correctly. If you update to the version `1.0.3` it should work as expected:

```js
server(ctx => {
  ctx.log.info('Simple info message');
  ctx.log.error('Shown on the console');
});
```

**Comment by klemola** [comment]
Thank you! I can verify that log messages work now with `1.0.3`.
