### ISSUE TITLE
Every POST request returns 403/Forbidden

### ISSUE THREAD

**Issue by gka** [franciscop/server#26]
Apologies if I am doing something wrong, but when I tried this simple server, POST requests always return 403/Forbidden.

```js
const server = require('server');
const { get, post } = server.router;

server({ port: 8080 }, post('/foo', ctx => 'test'));
```

If I swap the type to `get` on line 3 the request works just fine.

```
$ curl -X POST -v 'http://localhost:8080/foo'  
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /foo HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
< X-Powered-By: Express
< Vary: X-HTTP-Method, X-HTTP-Method-Override, X-Method-Override
< Content-Type: text/plain; charset=utf-8
< Content-Length: 9
< ETag: W/"9-PatfYBLj4Um1qTm5zrukoLhNyPU"
< set-cookie: connect.sid=s%3AU3PJ-nFxLLL1OrHYcYZmhFZ-AHDa_czV.1yPFK3MucYbpwdGZr%2BgYqZVkWYDNuC6t6ByS69%2FtGlc; Path=/; HttpOnly
< Date: Mon, 06 Nov 2017 21:58:17 GMT
< Connection: keep-alive
< 
* Connection #0 to host localhost left intact
Forbidden% 
```

shouldn't this just work out of the box?

**Comment by franciscop** [comment]
The POST request needs a [CSRF token](https://serverjs.io/documentation/router/#csrf-token) as explained [in the POST documentation](https://serverjs.io/documentation/router/#post-) and shown on both examples there.

A workaround if you are just testing things or you have a different kind of protection against CSRF is to disable this protection with the appropriate option:

```js
server({ port: 8080, security: { csrf: false } }, post('/foo', ctx => 'test'));
```

**Comment by franciscop** [comment]
Please let me know if this fixes things for you. I will leave this open until I improve the error message.

**Comment by gka** [comment]
it did fix it. thanks.
