### ISSUE TITLE
No routing if route handler returns undefined

### ISSUE THREAD

**Issue by brumm** [franciscop/server#28]
Hey,

coworker and I tested this thing out on a small api server and it's working well. Nice job!
During testing, my coworker (who is not super familiar with ES6 syntax) attempted to do this:

```js
server([
  get('/', ctx => { 'Hello world!' })
]);
```

which resulted in the server not routing to `'/'` because the handler method returned `undefined`.
We spotted the error fairly quickly and it did work in the end, but maybe server.js could warn if a handler is defined, but does not return anything?

**Comment by franciscop** [comment]
Interesting issue and solution. It does route to `/`, it is just that there is no reply so it goes undefined. I like your suggestion but I can see some issues, let me think about it, and thanks for the suggestion!

**Comment by franciscop** [comment]
I made the error message a lot more verbose in `1.0.9`, see [this commit](https://github.com/franciscop/server/commit/6d1fa391f6cbf16d12dfd92c37b3ade1d9c43f22). Please let me know if you think the changes are enough or not and if the message is clear enough.

**Comment by brumm** [comment]
Lookin good! I'll give it a shot tomorrow. Thanks for your work!

**Comment by franciscop** [comment]
Can I consider this fixed, @brumm ? Do you have any other question/suggestion?
