### ISSUE TITLE
How to authenticate

### ISSUE THREAD

**Issue by franckstifler** [franciscop/server#30]
I am curious on how to authenticate using server. I don't see how to configure my session store to be mongoDB using `connect-mongo`. A tutorial on how to this will be really helpful.

**Comment by franciscop** [comment]
You don't have access to the `session` that I know of, which is a known bug to be fixed. Meanwhile, you can do something like this:

```js
const mongoose = require('mongoose');
 
// Basic usage
mongoose.connect(connectionOptions);

server(server.utils.modern(session({
    store: new MongoStore({ 
      mongooseConnection: mongoose.connection 
    })
})));
```

You can use any express middleware by wrapping it with `server.utils.modern()`.

**Comment by franciscop** [comment]
Or even easier, you could use the native server store option:

```js
const mongoose = require('mongoose');
mongoose.connect(connectionOptions);

// See options docs
const options = {
  session: {
    store: new MongoStore({ 
      mongooseConnection: mongoose.connection 
    })
  }
};
server(options, ...);
```

**Comment by franciscop** [comment]
@franckstifler please let me know if that answers your question

**Comment by franckstifler** [comment]
@franciscop Let me get to my computer giving you a feedback in about 30min. I can make use of flassh messages too right?

**Comment by franckstifler** [comment]
The problem persists. Using connect-mongo documentation this is how I have to require the modules: ```
const session = require('express-session');
const MongoStore = require('connect-mongo')(session);```
I suppose the session is already set into server right? How are my then to pass the session to the next line? ` const MongoStore = require('connect-mongo')(???) `

**Comment by franciscop** [comment]
You are totally right, for this version you don't have access to `session`, which is definitely a bug. In the meantime, could you share some of your connection/startup code please? In the `connect-mongo` docs there are few examples that don't need the `session` object.

**Comment by franckstifler** [comment]
https://github.com/franckstifler/CheckAM/blob/master/index.js sorry for the late reply had to adjust some things before making a push. That is a project I am building powered by server.js.

**Comment by franciscop** [comment]
Did you try the snippet above?

```js
const mongoose = require('mongoose');
mongoose.connect(connectionOptions);

// See options docs
const options = {
  session: {
    store: new MongoStore({ 
      mongooseConnection: mongoose.connection 
    })
  }
};
server(options, ...);
```

Seems like you are using mongoose already from your project so you should be able to do that. You even have that [in line 23](https://github.com/franckstifler/CheckAM/blob/master/index.js#L23) (but it is commented):

```js
 // store: new MongoStore({ mongooseConnection: mongoose.connection })
```

Does that work? The line 4 in that situation should be like this:

```js
const MongoStore = require('connect-mongo');  // NO (server)
```

**Comment by franckstifler** [comment]
In deed I tried. The problem is actually in [line 4](https://github.com/franckstifler/CheckAM/blob/master/index.js#L4) because you must init connect-mongo with a session.

**Comment by franciscop** [comment]
You can skip it in line 4 and just load it without `(session)`, did you try that as well?

```js
const MongoStore = require('connect-mongo');  // NO (server)
```

**Comment by mariusk** [comment]
I believe I am struggling with the exact same issues wrt `connect-pg-simple`, and until the interfaces are cleared up I would suggest downplaying the Express session / middleware compatibility features a notch. Alternatively, improve the docs on how it should be done (no, I haven't figured it out unfortunately). It seems the pattern with initializing a store with a session object is pretty common..

**Comment by franckstifler** [comment]
In deed I loaded without session but it wont work, complaining that it needs a store.

**Comment by franciscop** [comment]
What about something like this? I think it should work properly now:

```js
const server = require('server');

// "server.session" contains the result of require('express-session');
// so you can inject it wherever it's needed
// Not to be confused with a current session
const MongoStore = require('connect-mongo')(server.session);
const store = new MongoStore(options);

server({ session: { store } }, ...);
```

It should be available in the latest `server@1.0.14` that was just released, please let me know what you think about this approach works for you or any other feedback!

**Comment by franckstifler** [comment]
Sorry for the delay. Testing right a way and giving you a feedback.

**Comment by franckstifler** [comment]
Good it works like charm now.

**Comment by franciscop** [comment]
Glad to hear! And thanks for the feedback 😇

**Comment by franckstifler** [comment]
Sure I can continue to work on my project. Think of creating a tutorial for that in the docs. I think it is very important.

**Comment by franciscop** [comment]
I did add it to [the documentation for session stores](https://serverjs.io/documentation/options/#session-stores), but I should add it to the Sessions in Production tutorial as well.
