### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by colelawrence** [franciscop/server#32]
Hi!
I was just curious if TypeScript definitions have been discussed for this project or are already available.

Thanks!

**Comment by franciscop** [comment]
@colelawrence I am not sure what you mean, I am not a big fan of TS in general myself. Do you mean for using TypeScript within server? Or for using server within your TS project?

**Comment by colelawrence** [comment]
Hey @franciscop !
I completely understand not liking TypeScript, I was just curious because a lot of editors use TypeScript definitions to make it easier to use other people's code (autocompletion and type checking etc) and not just for TypeScript projects, but also anyone that uses JavaScript benefits from TS definitions as well if their editor uses TypeScript to infer types and catch spelling errors. VSCode and WebStorm use TypeScript under the hood for JavaScript editing to enable autocompletion and rudimentary type checking, so having the definitions can improve adoption of server for those people.

There is a similar [discussion for TypeScript definitions for koa.js from a couple years ago](https://github.com/koajs/koa/issues/556), and what they did was essentially just publish a separate package [`@types/koa`](https://www.npmjs.com/package/@types/koa) to maintain the types in.

It doesn't have to live in this repo, and it doesn't have to happen. I just wanted to put the thought on your radar. 👍

**Comment by franciscop** [comment]
Ah that seems pretty interesting. I don't dislike it, I just prefer plain JS but I have no problem with types and I know some times they can be really helpful.

The issue though is on focus; I would have to learn a new whole paradigm even to get started implementing this. While I agree it is useful for some people, it is so low right now in my list of priorities that it'd basically mean "never" for me. After a small break I'll continue with the documentation and tutorials and then work on the `1.1`.

So I will leave this open for a while in case anyone wants to implement it. I think a separate package would be the best as the one you suggested (if that is a common way of doing this).

**Comment by ALyman** [comment]
I have started the process to get types up on the DefinitelyTyped registry.

I have a [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21713) for the "loadware" package that server depends on already up, and a [branch](https://github.com/ALyman/DefinitelyTyped/tree/server) that depends on that with the server types, which I'll upload as soon as the loadware PR lands.

**Comment by Sifawm** [comment]
@ALyman, first of all thanks. 

In your type definitions there are not definition for the function **socket** inside _server/router_.

Another thing that i have been able to check with my project is that this .d.ts dont leave export functions as:

```ts
export { get } from "server/router";
```

Same with functions inside _server/reply_.
If you like I can send a PR to your repo.

**Comment by ALyman** [comment]
@Sifawm: Huh, weird, looks like I forgot to commit & push the add for socket, I have gone and pushed [what I have for that](https://github.com/ALyman/DefinitelyTyped/commit/6766d05772bde00ecfcfe1ed96f0162c320210c4).

I would love to see a PR for server/router and server/reply -- I managed to forget that those exist, because I'm only using the ones hanging off as server.router and server.reply in my server-based project

**Comment by franciscop** [comment]
Any update on this? @ALyman could you fix the socket one? Did anyone get the router/reply done?

Finally, would some docs on the website make sense or is this something that will happen automatically for those using Typescript?

**Comment by Sifawm** [comment]
I am working with the @ALyman definitions to add the correct definitions to import server/reply and server/router directly. 

And he add the definitions to socket already. https://github.com/ALyman/DefinitelyTyped/blob/6766d05772bde00ecfcfe1ed96f0162c320210c4/types/server/index.d.ts#L118

**Comment by iddan** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24255

**Comment by sant123** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27579

PR merged.

**Comment by sant123** [comment]
This issue can now be closed.
