### ISSUE TITLE
Error in server.js

### ISSUE THREAD

**Issue by coderam** [franciscop/server#33]
when I test out your framework I noticed the following error with just the following in index.js:

`
// Import the library
const server = require('server');

// Answers to any request
server(ctx => 'Hello world');
`

I run "node ." on Ubuntu 16.04 and get the following error:

`
const Server = async (...middle) => {
                      ^^^
`

**Comment by franciscop** [comment]
What is your Node.js version? This seems like it might be a compatibility issue, since server requires Nose.js 7.6 or above (preferably 8.x).

**Comment by coderam** [comment]
v4.2.6

**Comment by franciscop** [comment]
So that is, you'd need to upgrade Node.js to be able to use server.js. I would recommend the 8.9.1. Server uses some more advanced and new features of Javascript that unfortunately are not retro-compatible.
