### ISSUE TITLE
Question on using different templating framework like nunjucks

### ISSUE THREAD

**Issue by coderam** [franciscop/server#34]
Thanks for this awesome framework.  It shall be as big as Django in the node family!

Quick question, if I do this:

```js
server([
  get('/', ctx => nunjucks.render('views/index.hbs', {chai: "chai"})),
  post('/', ctx => json(ctx.data)),
  get(ctx => status(404))
]);
```

"nunjucks.render()" and exclude your "render()" function, am I losing any kind of functionality?  It works ok, but is this the proper way?

Thanks!!

**Comment by franciscop** [comment]
Yes, that is perfect. Server was designed partly for this. What you are doing is:

```js
server(ctx => `
<!DOCTYPE html>
<html>
  ...
</html>
`);

```

You *are* losing a bit of functionality though, but only if you need it. From your code, you probably need it. This is the default locals such as the CSRF token. To fix this, you could do:

```js
server([ get('/', ctx => {
  const opts = Object.assign({}, ctx.locals, { chai: "chai" });
  return nunjucks.render('views/index.hbs', opts);
  }),
  post('/', ctx => json(ctx.data)), get(ctx => status(404))
]);
```

This way, with the Object.assign(), you will keep the CSRF token and other view variables visible for your templates.

Read the docs for the CSRF token: https://serverjs.io/documentation/router/#csrf-token . Where it says *The local variable is set by server.js*, you'd lose that with your method, but you can gain that back by extending the locals with the Object.assign().

**Comment by franciscop** [comment]
Ideally you'd use an express template engine for nunjucks that would basically do that assignment thing, but I couldn't find any that was as simple as any others and all of them require a bit of initial setup that is not easy with server.js
