### ISSUE TITLE
How to emit an event from outside the server

### ISSUE THREAD

**Issue by michaeljota** [franciscop/server#37]
Hi! I'm using Server for a small app, that should emit when a file changes. I'm using fs.watch for this, but I don't know how to emit the event. The examples that I've seen have only have response of events, but the server is never the source of one event.

**Comment by michaeljota** [comment]
The `server()` promise resolves to the context object that is being used in the responses, I think. However, it does have the `io` property to emit from anywhere in the application.

**Comment by franciscop** [comment]
Exactly, this is similar to this issue: https://github.com/franciscop/server/issues/48
