### ISSUE TITLE
sub fails on multi-level subdomains

### ISSUE THREAD

**Issue by nick-woodward** [franciscop/server#38]
### Description

The currently implementation of `sub` joins the subdomains incorrectly 
resulting in multi-level subdomains not working.

### Example

```js
const server = require('server');
const { status } = server.reply;
const { sub } = server.router;

server(
  sub('api.local', get('/', (ctx) => {
    return status(200).send('ok');
  })
);
```

### Relevant Code

The following code should return `api.local`, however instead it returns `local.api`.

https://github.com/franciscop/server/blob/d07cfe3b236f8d667fe27432810adefcae84a88c/router/sub.js#L4

**Comment by franciscop** [comment]
@nick-woodward it should be published under the 1.0.5 version, thanks a lot! I added a couple of extra tests for my own code since that part was a bit neglected.

For a future version I might add a wildcard subdomain like `sub('*.api', () => { .. })` but not right now.
