### ISSUE TITLE
can I mount an express app on specific path? 

### ISSUE THREAD

**Issue by garbin** [franciscop/server#41]
like offical documention on express http://expressjs.com/en/api.html does
```js
var express = require('express');

var app = express(); // the main app
var admin = express(); // the sub app

admin.get('/', function (req, res) {
  console.log(admin.mountpath); // /admin
  res.send('Admin Homepage');
});

app.use('/admin', admin); // mount the sub app
```
If yes, How?
If no, do you have plan to support this?

**Comment by franciscop** [comment]
What is the feature that you want, to be able to encapsulate a group of routes in a single app or to change the path from a single string on `.use()`? The first is easy, an *app* like that can be just an array of routes. The later is not possible and it is [a design decision explained here](https://github.com/franciscop/server/issues/18).

**Comment by garbin** [comment]
see https://github.com/koajs/mount

Is mount an express instance on a path possible? 

eg. there is a library https://github.com/bee-queue/arena exposes an `express server`, but I don't want to run this server `standalone`, I hope this server can be mount on `/queue_admin` because it should be. 

is it possible in `serverjs`?

**Comment by franciscop** [comment]
Hi @garbin , no it is not possible with `server` [as explained here](https://github.com/franciscop/server/issues/18). In the library https://github.com/bee-queue/arena that you linked there is an option to set the `basePath` though.
