### ISSUE TITLE
Issues using body-parser

### ISSUE THREAD

**Issue by yeager-j** [franciscop/server#42]
I may or may not be using your express middleware function correctly, but there it is.

```javascript
import * as server from 'server';
import * as bodyParser from 'body-parser';

const { modern } = server.utils;

server(
    modern(bodyParser.json({limit: '5mb'})),
    modern(bodyParser.urlencoded({limit: '5mb', extended: true})),
    ...
)
```

However I still receive this error:

```
ERROR { PayloadTooLargeError: request entity too large,
  message: 'request entity too large',
  expected: 170381,
  length: 170381,
  limit: 102400,
  type: 'entity.too.large' }```

**Comment by franciscop** [comment]
Hey, unfortunately you are not. Body-parser is already included by default so you only need to include the options on launch, not the middleware.

It expects it as this:

```js
server({
  parser: {
    limit: '5mb'
  }
});
```

I realize that this bit is not in the documentation so I'll leave this open until I get the chance to add it.

**Comment by franciscop** [comment]
Same with urlencoded (`body`), see this file as reference meanwhile: https://github.com/franciscop/server/blob/master/plugins/parser/index.js
