### ISSUE TITLE
Returning a status code with an empty body

### ISSUE THREAD

**Issue by justincy** [franciscop/server#46]
I want a specific route to return a 200 with an empty body. I've tried these two methods:

```js
get('/health', ctx => status(200))
```

```js
get('/health', ctx => 200)
```

They both work in that they return a 200 response but the body isn't empty (a default body of "OK" is returned) and they still trigger the "Your middleware did not return anything to the user." error that gets printed to the console.

How can I return an empty body without triggering the error message that gets printed to the console?

**Comment by franciscop** [comment]
The printing is completely true and should be fixed. It is a bug right now, I'll fix it ASAP.

The response body to the browser I am not sure whether it is a default HTTP thing or an espress thing. I'll have to dig deeper into this.

**Comment by franciscop** [comment]
Hi @justincy , this should be fixed by now. Please let me know if that works for you. I fixed both of the issues, the printing should be gone and answering with a status code just sends the status with an empty body.

**Comment by justincy** [comment]
Thanks for foxing it. However I ended up using something else so I'm able to test whether the changes worked. Sorry.

**Comment by franciscop** [comment]
Sure, no problem.
