### ISSUE TITLE
Provide a changelog

### ISSUE THREAD

**Issue by GeKorm** [franciscop/server#50]
### Description
A changelog would be very useful when deciding whether to upgrade this package. Even something automated like [changelog-maker](https://github.com/nodejs/changelog-maker) ([example](https://github.com/nodejs/node/releases)) would be good enough. I find it forces me to write better git messages anyway.

### Expected outcome
A list of changes or short description for every version, in the form of a CHANGELOG.md file or notes in the [releases](https://github.com/franciscop/server/releases) page.  
Example: Breaking changes in error handling. See xx for migration instructions.

### Actual outcome
No changelog provided

**Comment by franciscop** [comment]
I agree. Just never set to it, but with an automatic tool it should be easier. Would properly tagging the versions in Github be of any help? Or is a changelog strongly preferred?

**Comment by georgemandis** [comment]
My vote would be for a proper chaneglog. The automated one that @GeKorm pointed to would be a fine start.

**Comment by franciscop** [comment]
Reference just in case:

1.0.15 - Added session to the sockets. Fixed test and docs for jsonp.
1.0.14 - Session variable inside server `server.session` for initializing some stores and others.
1.0.13 - Make sure that the error always has an error code, even when empty. Used for matching.

**Comment by franciscop** [comment]
Working on this here: https://github.com/franciscop/server/releases
