### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by Greed1323** [franciscop/server#51]
Hi, i try to call my server with an another port, but i'm blocked by cross-origin security. And in documentation, i don't find a reference to cors.
I know resolve this issue on express:
https://enable-cors.org/server_expressjs.html

How can i resolve it on serverjs ?

thx.

**Comment by Greed1323** [comment]
Sorry, i don't seen the reply https://github.com/franciscop/server/issues/21

**Comment by franciscop** [comment]
It is documented here now: [CORS](http://localhost:3000/documentation/#cors).  Thanks for oppening the issue!
