### ISSUE TITLE
unable to send response for post request 

### ISSUE THREAD

**Issue by guruprasaad123** [franciscop/server#52]
Am using using [vue-resource](https://github.com/pagekit/vue-resource/blob/develop/docs/http.md) to send the post request to server.here's the code I used to send the post request.
  ```
     {
 this.$http.post('/register',{ 
        username:this.username,
        firstname:this.firstname,
       lastname:this.lastname,
       phoneno:this.phoneno  }
       ).then(response=>{
       console.log('responded...'+response.ok);
       }).then(error=>{
      console.log('Error...'+error);
       });
}
```
And the data is received successfully ,but am I unable to send the response here's how i did this.
```
server({
public:'public',
views:'pages',
port:80,
},[
    post('/register',ctx=>
    {
        if(!ctx.data)
        throw new Error('no data');
    console.log( ctx.data);         (**)
return status(200).send('success'); (***)
    }
    ),
   
]);
```
As for the proof that I have received the data sucessfully ,( **) as logged in the above code.I got this output in my console.(***) but the response is not sent which I don't know why.As I refered from [this](https://serverjs.io/documentation/reply/#status-)
```
{ 
username: 'guru001',
  firstname: 'guru',
  lastname: 'prasaad',
  phoneno: '09898454543'
 }
```
Am getting  **403 (Forbidden)**  in the browser console.
```

[Sun Dec 24 2017 14:11:22 GMT+0500 (Pakistan Standard Time)] ERROR { ForbiddenError: invalid csrf token
    at csrf (D:\workspace\@node\node_modules\csurf\index.js:112:19)
    at Promise (D:\workspace\@node\node_modules\server\src\modern\index.js:20:5)
    at new Promise (<anonymous>)
    at ctx (D:\workspace\@node\node_modules\server\src\modern\index.js:13:17)
    at module.exports.before.ctx (D:\workspace\@node\node_modules\server\plugins\security\index.js:52:49)
    at D:\workspace\@node\node_modules\server\src\join\index.js:42:27
    at <anonymous> code: 'EBADCSRFTOKEN' }

        mountpath: '/',
```

**Comment by franciscop** [comment]
You should send the CSRF token in your POST request. See the [corresponding documentation](https://serverjs.io/documentation/router/#csrf-token) for the POST requests with CSRF. You want to set the header `'csrf-token'` to the current csrf token, which can be obtained in different ways.

**Comment by guruprasaad123** [comment]
yes ,you are right ? that resolved the Issue thanks @franciscop

**Comment by franciscop** [comment]
Perfect, the error is not too clear but it is just a CSRF issue.
