### ISSUE TITLE
using csuf middle in server.js

### ISSUE THREAD

**Issue by guruprasaad123** [franciscop/server#53]
I trying to use [csurf](https://github.com/expressjs/csurf) as middleware in server.js , as mentioned in [docs](https://serverjs.io/documentation/#express-middleware) the code i tried.
```
const server = require('server');
// requirements
const { get, post} =require('server/router');

const {error} = server.router;

const {modern}=server.utils;
var sassMiddleware = require('node-sass-middleware')
let connect = require('connect');
let path=require("path");
let connect_app= connect();
let csrf = require('csurf');
const routes= require('./routes');

const mid_csrf=server.utils.modern(csrf);
const {status}= server.reply;

server(mid_csrf,{
public:'public',
views:'pages',
port:80,
parser: {
    cookie: {
      maxAge: 900000,
    }
  },
 // security: { csrf:csrf()  } ,
},routes);
```
the Error am getting...
```
(node:26772) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Only boolean, string, array or function can be middleware
(node:26772) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by franciscop** [comment]
The options should always come first, before any middleware. That is the error you are getting.

Also, csurf is already invluded by default. You can pass the appropriate options, as seen in the security documentation: https://serverjs.io/documentation/options/#security

**Comment by guruprasaad123** [comment]
thanks , But I want to use **node-sass-middleware** as middleware how do I , I have tried this code.
```
var sassMiddleware = require('node-sass-middleware')
let connect = require('connect');
let path=require("path");
et connect_app= connect();


connect_app.use(sassMiddleware({
    /* Options */
    src: path.join(__dirname, 'public'),
    dest: path.join(__dirname, 'public'),
indentedSyntax:true,
sourceMap:true,
 prefix:  '/stylesheets'  
}));// pages data
server(
   connect_app,
    {
public:'public',
views:'pages',
port:80,
parser: {
    cookie: {
      maxAge: 900000,
    }
  },
 // security: { csrf:csrf()  } ,
},routes);
```
for this too am getting the below mentioned _Error_.
```
(node:26772) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Only boolean, string, array or function can be middleware
(node:26772) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by franciscop** [comment]
As I said, *The options should always come first, before any middleware*. This means when launching `server()` you should set this order:

```js
server({
    public:'public',
    views:'pages',
    port:80,
    parser: { cookie: { maxAge: 900000 } }
  },
  mid_connect,
  routes
);
```

So your full script would be something like this:

```js
const path = require("path");
const sassFactory = require('node-sass-middleware');

const sass = sassFactory({
  /* Options */
  src: path.join(__dirname, 'public'),
  dest: path.join(__dirname, 'public'),
  indentedSyntax:true,
  sourceMap:true,
  prefix:  '/stylesheets'  
});

server({
  public:'public',
  views:'pages',
  port:80,
  parser: { cookie: { maxAge: 900000 } }
},
  server.utils.modern(sass),
  routes
);
```

**Comment by guruprasaad123** [comment]
thanks, that worked !

**Comment by franciscop** [comment]
It is [a bit above that](https://serverjs.io/documentation/#basic-usage): *The main function accepts first an optional object for the options, and then as many middleware or arrays of middleware as wanted*.

Also in [the options documentation](https://serverjs.io/documentation/options/#argument) in bold: *The alternative to the environment variables is to pass them **as the first argument** when calling server()*.

Do you think it could be added somewhere else or explained differently?

**Comment by guruprasaad123** [comment]
I have quickly read the _docs_, so I did'nt notice it sorry. Maybe ,combining the both Examples and showing a  _preview_  will help us visually see and understand the feature at Ease and quickly.
