### ISSUE TITLE
Access ctx.session from websocket?

### ISSUE THREAD

**Issue by paulrobello** [franciscop/server#55]
Is there any way to access the ctx.session object from a websocket handler callback?

```js
const connect = ctx => {
  if (ctx.session){  // <--------------- This does not seem to exist in socket related callbacks
    console.log('Yay Session!',ctx.session);
  }else{
    console.log('Booo no session');
  }
  ctx.io.emit('session', ctx.session);
};

server(serverOpts, [
  cors,
  get('/', ctx =>render('index.html'),
  get(ctx => status(404)),
  socket('connect', connect),
  error(ctx => status(500).send(ctx.error.message))
]).then(ctx => {
  console.log(`Server launched on http://localhost:${ctx.options.port}/`);
});
```

**Comment by franciscop** [comment]
No that I know of right now. This is a legitimate bug/new-feature.

**Comment by paulrobello** [comment]
If it helps, ctx.socket.handshake.headers.cookie gets you access to the cookie info to get the sid.
Is there socket related middleware?

**Comment by franciscop** [comment]
Yes, it looks like this should fix it: 

https://stackoverflow.com/questions/25532692/how-to-share-sessions-with-socket-io-1-x-and-express-4-x

Now, for this we should fix this one first: https://github.com/franciscop/server/issues/30

**Comment by paulrobello** [comment]
I have shared sessions works using the following....


'use strict';

require('dotenv').config();
const uuid = require('uuid/v4');
const server = require('server');
const {modern} = server.utils;
const {get, socket, error} = server.router;
const {render, status, header} = server.reply;

const expSession = require('express-session');
const RedisStore = require('connect-redis')(expSession);

const redis = require('redis');
const redisClient = redis.createClient(process.env.REDIS_URL);

const sessionMiddleware = expSession({
  secret: process.env.SECRET,
  store: new RedisStore({url: process.env.REDIS_URL,client:redisClient}),
  genid: () => {
    return uuid();
  },
  resave: true,
  saveUninitialized: true,
  rolling: true,
  proxy: true,
  cookie: {
    httpOnly: true,
    secure: false
  },
  name: 'par.sid'
});
console.log(sessionMiddleware);

redisClient.on('error', (err) => {
  console.error('RedisClientError',err);
});

const cors = [
  ctx => header('Access-Control-Allow-Origin', '*'),
  ctx => header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept')
];

const connected = ctx => {
  console.log(ctx.socket.client.request.session); // <----- this is how you access the session object
  if (ctx.socket.client.request.session) {
    console.log('socket session', ctx.socket.client.request.session);
    console.log('socket user', ctx.socket.client.request.session.user);
    if (!ctx.socket.client.request.session.user){ // <--- create user in session for testing
      ctx.socket.client.request.session.user={username: 'probello', name: 'Paul Robello'};
      ctx.socket.client.request.session.save();
    }
    ctx.socket.emit('user', ctx.socket.client.request.session.user);
  } else {
    console.log('socket no session');    
  }  
};

const sendMessage = ctx => {
  ctx.io.emit('message', ctx.data);
};
const serverOpts = {
  port: 3000,
  views: '../dist',
  secret: process.env.SECRET,
  session: false
};
server(serverOpts, [
  cors,
  modern(sessionMiddleware),
  get('/', ctx => {
    if (ctx.session) {
      console.log('get yay session');
    } else {
      console.log('get booo no session');
    }
    // return 'nope';
    return 'hello world'+JSON.stringify(ctx.session.user); //render('index.html');
  }),
  get(ctx => status(404)),
  socket('connect', connected),
  socket('message', sendMessage),
  error(ctx => status(500).send(ctx.error.message))
]).then(ctx => {
  console.log(`Server launched on http://localhost:${ctx.options.port}/`);
  ctx.io.use(function (socket, next) {
    sessionMiddleware(socket.request, socket.request.res, next);
  });
});

**Comment by franciscop** [comment]
That is a really long piece of code. Server is supposed to do many of the things that you are making manually. The latest release 1.0.15 should have `ctx.session` available within `socket()` callbacks. [See full working example](https://github.com/franciscop/server/blob/master/examples/websocket/index.js):

```js
const server = require('../../server');
const { get, socket } = server.router;
const { render } = server.reply;

server(
  get('/', ctx => {
    ctx.session.counter = ctx.session.counter || 0;
    return render('index.html');
  }),
  socket('connect', ctx => {

    // Emit an event every second with +1 on the session
    setInterval(() => {

      // Increment the counter
      ctx.session.counter++;

      // For socket.io you need to manually save it
      ctx.session.save();

      // Send the value to the currently connected socket
      ctx.socket.emit('message', ctx.session.counter);
    }, 1000);
  })
);
```
