### ISSUE TITLE
Best way to determin if request is from normal HTTP or Socket?

### ISSUE THREAD

**Issue by paulrobello** [franciscop/server#59]
I have have a single function that that i use for both http POST and websocket event.
I was wondering what the best / cleanest way is to determine if the request is coming from the post or the socket handler?

**Comment by franciscop** [comment]
Interesting, I tried to make server to avoid needing this as much as possible. `ctx.data` should be the same, but with POST you will have `ctx.method === 'POST'` while with socket you don't have anything there (but will be `SOCKET` in 1.1). So the cleanest way is checking if the method is `POST`, I think this is the better way.

```js
module.exports = ctx => {
  if (ctx.method === 'POST') {
    // ...
  } else {
    // ...
  }
};
```

**Comment by franciscop** [comment]
Note: I can think of at least 3 more ways, but I think this is the cleanest. Please let me know if this doesn't work.

Also, similar to front-end and depending why you want to know, you might think of it in a *feature-detection* way: `if (hasFeatureIWant()) {} else {}`
