### ISSUE TITLE
.slice() of undefined when I am throwing an error  

### ISSUE THREAD

**Issue by LoickVirot** [franciscop/server#64]
### Description

I got an unhandled error when I try to throw an error into a middlewareto manage it with the router ` error()`.

### Expected outcome
In this example, I expected this into my console
```
{ user.noname: No username detected
    at mid2 (/src/app/index.js:12:15)
    at /src/app/node_modules/server/src/join/index.js:40:27
    at <anonymous> name: 'user.noname', params: { '0': 'undefined' } }
```

### Actual outcome

Here is my code, inspired from the documentation :
```javascript
const mid2 = ctx => {
  const err = new Error('No username detected');
  err.name = 'user.noname';
  throw err;
};

const handleUser = error('user', ctx => {
  console.log(ctx.error);
});

server(mid2, get('/', ctx=>{return json('hello world')}), handleUser);
```

And my console : 
```
[Tue Jan 23 2018 22:11:34 GMT+0000 (UTC)] WARNING There is an unhandled error:
[Tue Jan 23 2018 22:11:34 GMT+0000 (UTC)] ERROR TypeError: Cannot read property 'slice' of undefined
at Function.generic.error (/src/app/node_modules/server/router/error.js:17:45)
at /src/app/node_modules/server/src/join/index.js:34:33
at <anonymous>
```
BUT, if I don't try to get only 'user' errors, there is no problems : 
```javascript
const handleUser = error(ctx => {
  console.log(ctx.error);
});
```
```
{ user.noname: No username detected
    at mid2 (/src/app/index.js:12:15)
    at /src/app/node_modules/server/src/join/index.js:40:27
    at <anonymous> name: 'user.noname', params: { '0': 'undefined' } }
```

### System Information

**OS:** Kubuntu 17.10.01

**Node Version:** v9.3.0

**Server.js Version:** 1.0.4

**Comment by franciscop** [comment]
If you update to 1.0.13 that error should not happen anymore as @SidneyNemzer pointed. However, the documentation was outdated (just updated it!), it should be `error.code = 'user'` instead of `error.name = 'user'`:

```js
const server = require('../../');
const { get, error } = server.router;

const mid2 = ctx => {
  const err = new Error('No username detected');
  err.code = 'user.noname';
  throw err;
};

server(
  mid2,
  get('/', ctx=> json('hello world')),
  error('user', ctx => {
    console.log(ctx.error);
    return 'Matched! :)';
  }),
  error(ctx => {
    console.log(ctx.error);
    return 'Not matched! :(';
  })
);
```

Reference:

- [**Created bug demo**](https://github.com/franciscop/server/tree/master/examples/bug64) and confirmed the bug: change the `code` for `name` in the demo and it doesn't work anymore.
- [**Updated documentation**](https://serverjs.io/documentation/router/#error-).
- [**Added test**](https://github.com/franciscop/server/blob/master/router/integration.test.js#L204).

**Comment by franciscop** [comment]
Note that I'm doing some work on [the whole error handling](https://github.com/franciscop/server/tree/master/error) (ignore that README.md though), but still need to test it quite a bit more before it's ready for production.

**Comment by LoickVirot** [comment]
I'll try that. Thank you very much ;)

**Comment by franciscop** [comment]
Thank you, please let me know if it doesn't work. I closed this since I could reproduce and fix the issue locally, if it is not fixed for you feel free to reopen, add a comment or open a new issue.
