### ISSUE TITLE
Clustering & worker nodes

### ISSUE THREAD

**Issue by adrian2x** [franciscop/server#66]
### Description

No docs on how to load balance or cluster or run parallel processes?

### Expected outcome

Docs should exist

### Actual outcome

!Docs

**Node Version:** v8.9.1

**Server.js Version:** 1.0.14

**Comment by franciscop** [comment]
I agree, unfortunately it is not a priority right now or even for the whole 1.x cycle. I plan to address it on the 2.x. The key qhote is [in the Advanced documentation](https://serverjs.io/documentation/#advanced-topics):

> 

Feel free to open a PR adding some docs though! They'd fit either in the tutorials or in the main Documentation README as a new section.

**Comment by franciscop** [comment]
I agree, unfortunately it is not a priority right now or even for the whole 1.x cycle. I plan to address it on the 2.x. The key qhote is [in the Advanced documentation](https://serverjs.io/documentation/#advanced-topics):

> There is a lot of basic to mid-difficulty documentation to do until we even get here.

Feel free to open a PR adding some docs though! They'd fit either in the tutorials or in the main Documentation README as a new section.
