### ISSUE TITLE
Hot Module Reload?

### ISSUE THREAD

**Issue by karneaud** [franciscop/server#68]
I'm trying to use this package in development mode but not sure how to integrate web pack or HMR into it. Does your package support hot reload?

**Comment by SidneyNemzer** [comment]
There's been some discussion about HMR in #61

**Comment by franciscop** [comment]
Yes, please look into https://github.com/franciscop/server/issues/61. What do you intend to use for HMR? Webpack?

**Comment by karneaud** [comment]
@franciscop  @SidneyNemzer  correct. Looked at the topic and I have a vague understanding as to what you guys did. Care to explain by example?

**Comment by franciscop** [comment]
server.js does not have HMR natively, but with the code on #61 you might be able to work your way through. Unfortunately I don't know about HMR, I just improved the code in that issue slightly to fit server.js api better so you'll have to work on this. Feel free to ask for more specific issues, file bugs, look [at the documentation](https://serverjs.io/documentation) or ask a question on StackOverflow, but asking me to give you examples is not within the scope of OSS.
