### ISSUE TITLE
Unable to access index.pug route

### ISSUE THREAD

**Issue by karneaud** [franciscop/server#69]
### Description

The server stalls when accessing the intended route

### Expected outcome

Server response with html page

### Actual outcome

Server outputs "Hello world" with the following route

`server({},ctx => "Hello World")`
Server stall when accessing 

`server({}, [ get('/', () => render('index.pug'))])`
### Live Demo

Code

```
// Import the library
const server = require('server');
const { get } = server.router;
const { render } = server.reply;
const routes = require('./routes.js');
// Launch the server to always answer "Hello world"
server({ port: 8000, log: {
    level: 'info',
    report: (content, type) => {
      console.log(content);
    }
  } }, [
    get('/', () => render('index.pug'))
  ]);
```

### System Information

**OS:**  Docker

**Node Version:** v8.9.1

**Server.js Version:** 1.0.14

**Comment by karneaud** [comment]
found out my views folder was not referenced properly

**Comment by franciscop** [comment]
It should throw a pretty clear error in that situation, I am reopening this until the error is clear.

**Comment by karneaud** [comment]
Its ok...needed to adjust my folder structure.
