### ISSUE TITLE
Issues with Jest Unit testing

### ISSUE THREAD

**Issue by karneaud** [franciscop/server#70]
### Description

Router fails to load during unit testing

### Expected outcome

`jest --coverage` 

seems to stall 

### Actual outcome

test script should run and conclude tests

### Live Demo

package.json
```
{
  "name": "decibel-game",
  "version": "1.0.0",
  "description": "Multiplayer Simon Says Game",
  "main": "index.js",
  "scripts": {
    "server-server": "node index.js",
    "test": "jest --coverage --forceExit",
    "postinstall" : "npm run server-server"
  },
  "dependencies": {
    ....,
    "server":"*"
  },
  "devDependencies": {
    "jest":"*"
  },
  "author": "",
  "license": "ISC"
}
```

tests/server.tests.js
```
const s = require('server');

test('routes it not null', () => {
    expect(s).toEqual(require('server'));
  }
);
```

`npm test` 

results
>  RUNS  tests/server.test.js

stalls here. If I remove `require('server')` I get

>  FAIL  tests/server.test.js
> ✕ routes it not null (19ms)

>  ● routes it not null

>    ReferenceError: s is not defined

>      1 | test('routes it not null', () => {
>    > 2 |     expect(s).toEqual(require('server'));
>      3 |   }
>      4 | );
 >     5 |

>      at Object.<anonymous>.test (tests/server.test.js:2:12)

> Test Suites: 1 failed, 1 total
> Tests:       1 failed, 1 total
> Snapshots:   0 total
> Time:        5.597s
> Ran all test suites.
> ----------|----------|----------|----------|----------|----------------|
> File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
> ----------|----------|----------|----------|----------|----------------|
> All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
> ----------|----------|----------|----------|----------|----------------|
> npm ERR! Test failed.  See above for more details.

not sure what I am doing wrong here..........what can you advise?

### System Information

**OS:** Docker

**Node Version:** v8.9.4

**Server.js Version:** 1.0.17

**Comment by franciscop** [comment]
You only have those lines in your whole test?

```js
const s = require('server');

test('routes it not null', () => {
    expect(s).toEqual(require('server'));
  }
);
```

Strange that if fails, for me the same code passes without an issue:

![pass](https://user-images.githubusercontent.com/2801252/35806018-683160e6-0ac1-11e8-9abd-8d092101da70.png)

If you were actually launching the server I'd have a couple of tips, but just failing at requiring it is pretty strange. Could you provide more context? Also, what happens when you wait for ~30 seconds? Does jasmine timeout (5s by default I believe) trigger?

**Comment by karneaud** [comment]
Apparently jasmine was the culprit. Had to remove and re-install for some reason. *shrugs*
