### ISSUE TITLE
Security incident report

### ISSUE THREAD

**Issue by franciscop** [franciscop/server#73]
## Fix

Make sure that you are using `server 1.0.x`, the stable branch. To force this, do:

```bash
npm install server@1.0
```

## What happened?

If you installed server.js recently from scratch you have to upgrade it, since there is an issue that makes the sessions of all your users shared.

This is a two side issue:

- **Shared session**: The versions `1.1.0-alpha.1` and `1.1.0-alpha.2` have a bug that initiates no session for the user, but all of the session information is shared.
- **Unstable releases**: The alpha releases were not properly being tagged as `@next` so they are installable with `npm install server`.

It does not affect you if you had server already installed on the `1.0.x` version, it only affects installations from scratch.

## Timeline

> Tokyo times:

- 15 January 7pm: server.js version `1.1.0-alpha.1` gets released. This has both issues but I am unaware of either. Note: my birthday :(
- 14 February 10am: [an issue is opened](https://github.com/franciscop/server/issues/72) explaining reporting this as a bug (thank you @paulrobello).
- 15 February 1pm: I test this and find it is a bug. However, I wrongly assume it belongs to the alpha and does not affect many people.
- 16 February 7am: after further comments, I become aware that alpha versions are the ones being installed by default.
- 16 February 7am: I fix it as well as I can and publish the fixes, both in the `1.1.0-alpha.3` (properly tagged as `@next` now) and in the `1.0.18` (tagged as `@latest`).

## Mitigation

To avoid this issue or anything like this in the future, this is my plan:

1. [x] Add a notice in the homepage for 1 month besides the `npm install server` command.
2. [ ] ~~~Send an email to the users subscribed to Mailchimp so they can update their server versions.~~~
3. [x] Use a package release tool such as `np` instead of `npm publish`. I haven't read about it too much yet but I think it'll have sane defaults.
4. [x] Add tests for this behaviour. Have to fix `.alive()` in the testing to make it work properly, I suspecting it being buggy so it delayed my fix.

## Comments

I do feel betrayed by this stupid behaviour from `npm publish` and `npm install`, [see here for the full horror story](https://medium.com/@mbostock/prereleases-and-npm-e778fc5e2420). Still, ultimately it should be me who makes sure the release is being released properly.

I have to go back to work (lunch break), but I'll do the other 3 pending tasks as soon as I get out. I thought that this report and homepage notice was the most urgent fix I could do right now.

**Comment by Download** [comment]
My hat is off to you sir for this very honest and detailed incident report.

I have to admit I fell for the 'npm install installs alpha versions' problem as well. To make matters worse, there are actually articles out there saying that NPM is smart and does 'the right thing'... and so it does in recognizing that 1.0.0-alpha is a lower version than 1.0.0 (there are systems that do this wrong... looking at you [OSGi](https://www.osgi.org/wp-content/uploads/SemanticVersioning.pdf)). But imho it does not do the right thing when it installs an alpha by default! I hope they will one day fix this behaviour.
