### ISSUE TITLE
Improved testing

### ISSUE THREAD

**Issue by franciscop** [franciscop/server#74]
Hi everyone, I am improving the testing, both internally and externally. If anyone wants to learn about testing let me know and I'll do a 1-on-1 helping you on your testing and gather opinions at the same time.

Now, I am thinking about this syntax, what do you think? Split into two files so one is for running the server and the other for testing it:

```js
// index.js
const server = require('server');

module.exports = server(() => 'Hello world');
```

```js
// api.test.js (or any other name)
const app = require('./index');
const run = require('server/test');

describe('homepage', () => {
  it('says hello', async () => {
    const res = await run(app).get('/');
    expect(res.body).toBe('Hello world');
  });
});
```

> Note: it works but it is not published yet so you'd have to clone the repo to try it.

What do you think about this API for testing? I think it is pretty nice but haven't tested it with my projects yet.

**Comment by vorticalbox** [comment]
I wish just about to ask for this. I am trying to run tests using mocha/chai for a project i'm working on at work but I am getting 

TypeError: Cannot read property 'address' of undefined

**Comment by franciscop** [comment]
Hey @vorticalbox great! I am writing the [testing documentation here](https://github.com/franciscop/server/tree/plugins/docs/documentation/testing). Are you writing `server` tests with mocha/chai? Could you please share more information like the full error log? And the code where this error happens?

I am finishing a testing module that will be easy to use with any testing framework, and then document the most popular ones. I will start by Jest (since it's the internal one for server.js) but Mocha/Chai are really similar, so they will follow shortly.

**Comment by vorticalbox** [comment]
basically the same as you have wrote in the first one but testing my routes.

**Comment by franciscop** [comment]
Okay there seems to be two issues here:

1. `server` in your example is a Promise, so we have to make it resolve first (launch the server) and then we can do something with it.
1. Even then, we will need to access the property `app` from the resolved value (`ctx`), since that contains the express app as referenced in the Chai documentation.

Let's make it resolve first. For this, you could add a `beforeAll` with an await, a `await` inside each of your tests or just resolve the promise manually. Let's do the latter since you are using `done()` instead of `async`/`await`. For this, we do:

```js
describe('Timeline Worker - configs', () => {
    it('v1/config', (done) => {
        // We wait until server is resolved (launched)
        Promise.resolve(server).then(ctx => {
          // We use the property `app` inside ctx
          chai.request(ctx.app)
              .get('/v1/config')
              .end((err, res) => {
                  res.should.have.status(200);
                  done();
              });
        });
    });
});
```

I think `Promise.resolve()` might not be needed for whenever you have multiple tests, but [in this example resolved twice](https://jsfiddle.net/9j6g5gn5/3/) I needed to `.clone()` them so I'm wrapping it just in case.

Please let me know whether that works or not :smile:

**Comment by vorticalbox** [comment]
This works perfectly.
