### ISSUE TITLE
Please make sessions work right out of the box

### ISSUE THREAD

**Issue by coderam** [franciscop/server#75]
I really love server.js but session are such a pain.  Can you make them super simple somehow, like:

const session = server.session;

and then anywhere you set a session value, session.name = val; it should just work without configuring a backend (use some kind of default session handling backend).

**Comment by coderam** [comment]
thanks :)

**Comment by franciscop** [comment]
Could you explain a bit more please? Sessions *should* work out of the box as you describe in the best way possible. But to work properly you need a permanent store which is not available in most Node.js deployment/workflow (like Redis) and a secret which should be manually generated (which is an indirect consequence of the previous issue).

**Comment by coderam** [comment]
@franciscop shall try and test this on alpha3 as soon as my templating is restored using the new engine for templating.

**Comment by franciscop** [comment]
@coderam could you test this? Is this fixed?

**Comment by coderam** [comment]
@franciscop as mentioned as soon as nunjucks is fixed (basically ctx.csrf and other ctx variables are not showing up so I attempted alpha3 but still not really functioning).  that issue was closed probably by mistake.  Once that is fixed I shall test sessions using one of the backends mentioned.

**Comment by franciscop** [comment]
This seems to be a non-issue? Not sure why/how it was an issue initially, but would need more code or better explanation to reproduce.
