### ISSUE TITLE
Readme.md "Sponsor the Project" link out of date

### ISSUE THREAD

**Issue by hostdos** [franciscop/server#8]
In the Readme.md file the "Sponsor the Project" link in the last paragraph links to a non-existent file.

**Comment by franciscop** [comment]
I was just about to pass a 404 checker tool, thanks!

**Comment by franciscop** [comment]
@hostdos oh, are you interested in sponsoring the project?

**Comment by hostdos** [comment]
@franciscop not really, sorry :sweat_smile: I saw your HN comment and clicked around. I just hate seeing hard working people miss out on possible rewards just because a link broke ;)

**Comment by franciscop** [comment]
@hostdos no problem at all :smile:
