### ISSUE TITLE
Handling Files

### ISSUE THREAD

**Issue by vorticalbox** [franciscop/server#80]
### Description

Documentation has very little on how to handle files other than logging out its name.

### Expected outcome

would be nice for the documentation to show about saving files or doing something with the file content.

### System Information

Windows 10 :(

**Node Version:** v8.9.4

**Server.js Version:** 1.0.18

**Comment by franciscop** [comment]
hey @vorticalbox thanks for the issue! You are totally right, I was planning on writing docs at some points with this functionality. Are you using AWS or [Cloudinary](https://cloudinary.com/) by any chance? The former is the most popular and I've used the later (since they have [a generous free tier](https://cloudinary.com/pricing)), so I could start by either of those.

The most [relevant documentation in server.js](https://serverjs.io/documentation/context/#-files) is certainly lacking, just displaying the file in your filesystem:

```js
const mid = post('/profilepic', ctx => {
  // This comes from the "name" in the input field
  console.log(ctx.files.profilepic);
  return redirect('/profile');
});
```

I'll try to create the tutorial over the weekend.

**Comment by dannluciano** [comment]
I am using [minio](https://minio.io/) for personal private S3 API like.
The best away to upload files is in the client side see this: https://docs.minio.io/docs/upload-files-from-browser-using-pre-signed-urls

Upload file for your own server only works in little cases.

**Comment by vorticalbox** [comment]
My service doesn't have a client side it's an api only.

**Comment by franciscop** [comment]
@vorticalbox to make sure things are working so far, does this work so far? Can you see the picture name in the filesystem with something like this?

```js
const mid = post('/profilepic', ctx => {
  // This comes from the "name" in the input field
  console.log(ctx.files.profilepic);
  return redirect('/profile');
});
```

Note: you will very likely need to [disable the CSRF security](https://serverjs.io/documentation/options/#security) if you are not doing cookie-based auth (not common with APIs).

**Comment by vorticalbox** [comment]
I can see the file name that part works, just wondering how to do things with the files the api gets.

**Comment by sammychiang** [comment]
i directly handle the file by the it's path 
file path is :

`ctx.req.files.voice.path  //voice is the key of the file`

then you can read the file by "fs" api of node

**Comment by franciscop** [comment]
Code is ready, see screenshot:

![gallery2](https://user-images.githubusercontent.com/2801252/37325597-e0ece33a-26d1-11e8-9d67-f457830898e9.png)

Here is the repository: https://github.com/franciscop/server-tutorial-upload

I will try to clean up and finish the tutorial ASAP.

**Comment by franciscop** [comment]
@vorticalbox here is the draft: https://github.com/franciscop/server/tree/plugins/docs/tutorials/upload-files
