### ISSUE TITLE
middleware fails to return

### ISSUE THREAD

**Issue by vorticalbox** [franciscop/server#85]
### Description

when using .then and .catch the middle-ware doesn't wait and returns nothing. Using async/await works correctly

### Expected outcome

middle should wait and before returning

### Actual outcome

returns nothing

### Example

```
const server = require('server');
const { get } = server.router;
const { json, status } = server.reply;


const Customer = require('../../helpers/customer');

const getDetails = async(ctx) => {
    Customer.getDetails(ctx.params.name)
    .then((data) =>{
        return json(data)
    }).catch((error) =>{
        return status(500).json(error)
    })
};


module.exports = [
    get('/v1/licence/get/:name', getDetails),
];
```

### System Information

Ubuntu 17.10

**Node Version:** v8.10.0

**Server.js Version:** 1.0.18

**Comment by SidneyNemzer** [comment]
I believe you just need to return the promise from the middleware function

```
const getDetails = (ctx) => {
  return Customer.getDetails(ctx.params.name)
    .then((data) =>{
      return json(data)
    }).catch((error) =>{
      return status(500).json(error)
    })
};
```

Also, since you aren't using `await` in that middleware function, it doesn't need to be `async`. Although I don't think it really matters.

**Comment by vorticalbox** [comment]
The async was there as I copied my code I changed to await. That would make sense returning the promise

**Comment by franciscop** [comment]
** @SidneyNemzer answer is the correct answer and the best way to solve it**; to make it wait, you have to tell server you are not done somehow. This means either returning a promise or making the whole function async/await. You might need to promisify some things if they are using callbacks:

```js
// Same code with the newer util.promisify: http://2ality.com/2017/05/util-promisify.html
const myTask = require('util').promisify(doAsyncTaskWithCallback);
const getDetails = async (ctx) => {
  const value = await myTask(ctx.params.name);
  // ...
};
```

There are a couple more patterns you *might* need at some points, but I recommend trying to avoid them and use async/await as much as possible:

```js
// Mixing callbacks and server.js
const getDetails = (ctx) => {
  return new Promise((resolve, reject) => {
    doAsyncTaskWithCallback(ctx.params.name, (error, value) => {
      if (error) return reject(error);
      resolve(value);
    });
  });
};
```

You can always use express middleware with [modern()](https://serverjs.io/documentation/#express-middleware):

```js
const getDetails = modern((req, res, next) => {
  Customer.getDetails(req.params.name)
    .then((data) => res.json(data))
    .catch((error) => res.status(500).json(error))
});
```

Feel free to reopen or ask more questions :+1:
