### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by karlll** [franciscop/server#87]
### Description

After cloning repo & `npm install`, `npm test` fails as below

```
Summary of all failing tests
 FAIL  src/config/unit.test.js
  ● Parses the .env correctly › works with pseudo-json

    expect(received).toBe(expected)

    Expected value to be (using ===):
      "{\"a\"}"
    Received:
      undefined
```
### System Information

**OS:** MacOS High Sierra

**Node Version:** v9.8.0

**Server.js Version:** 1.0.18

**Comment by franciscop** [comment]
Oh yeah, you'll need the `.env` for testing, forgot to set it up for those cloning the project! Please put this in your `.env`:

```
# Test variables
TEST=bbb
TESTB=5
TEST X=0
TEST00=abc
Test01=abc
TesT02=abc
test03=abc

TEST10=abc
TEST11=Abc
TEST12=AbC
TEST13=ABC

TEST20=10
TEST21=-10
TEST22=10.5
TEST23=10e5

TEST30=true
TEST31=True
TEST32=TruE
TEST33=TRUE

TEST40={}
TEST41=[]
TEST42={"a":"b"}
TEST43=["a", "b"]
TEST44={"a"}
```

But note that the more advanced examples (auto-parsing) are still WIP and nowhere to be found in the docs.

**Comment by karlll** [comment]
Thanks for clarifying!

**Comment by franciscop** [comment]
@karlll please let me know if it works now if you test it again👌

**Comment by karlll** [comment]
@franciscop - the test works when I set the environment you mentioned above.
