### ISSUE TITLE
Error: listen EADDRINUSE :::8000

### ISSUE THREAD

**Issue by karneaud** [franciscop/server#89]
### Description

I'm using Unable to restart server using nodemon from webpack build event

my server file

```
// Import the library
const server = require('server');
const routes = require('./routes.js');
// Launch the server to always answer "Hello world"
server({ port: 8000, log: {
    level: 'info',
    report: (content, type) => {
      console.log(content);
    }
  } }, routes).then(async ctx => {
  // do something...
  await ctx.close();
  // now it is closed! without the await it might not yet have closed
  // Note: if a websocket is connected it won't close, see the socket plugin tests :(
});
```
### Expected outcome

Should be able to restart server from nodemon 

```
compiler.hooks.compile.tap('NodeBrowserSyncWebpackPlugin', () => {
            if (this.isWebpackWatching) {
                nodemon(this.nodemonOptions).on('start', () => {
                    console.log(`[${chalk.blue('Nodemon')}] ${chalk.cyan('Restarting...')}`);
                    setTimeout(() => {
                        this.browserSync.reload();
                    }, 500);
                });
            }
        });
```
### Actual outcome

I get the following trying to reload

> [Browsersync] Reloading Browsers...
nod(node:140) UnhandledPromiseRejectionWarning: Error: listen EADDRINUSE :::8000
node-serverjs |     at Server.setupListenHandle [as _listen2] (net.js:1346:14)
node-serverjs |     at listenInCluster (net.js:1387:12)
node-serverjs |     at Server.listen (net.js:1475:7)
node-serverjs |     at Function.listen (/usr/src/app/node_modules/express/lib/application.js:618:24)
node-serverjs |     at Promise (/usr/src/app/node_modules/server/plugins/express/index.js:59:26)
node-serverjs |     at new Promise (<anonymous>)
node-serverjs |     at listen (/usr/src/app/node_modules/server/plugins/express/index.js:58:18)
node-serverjs |     at Server.Promise.all.hook.map.listen (/usr/src/app/node_modules/server/server.js:62:55)
node-serverjs |     at Array.map (<anonymous>)
node-serverjs |     at Server (/usr/src/app/node_modules/server/server.js:62:41)
node-serverjs | (node:140) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
node-serverjs | (node:140) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### System Information

**OS:** Docker Linux

**Node Version:** v8.9.1

**Server.js Version:** ~1.0.17

**Comment by franciscop** [comment]
@karneaud could you please upgrade to 1.0.18 and try again? Or with `1.1.0-alpha.8`? I am a at a loss since I haven't used Webpack with back-end, normally I use `nodemon`. But perhaps it might have something to do with the websockets connection. Also please try to update the timeout to `2000`?

**Comment by franciscop** [comment]
@karneaud did it work on either `1.0.18` or `1.1.0-alpha.8`?

**Comment by karneaud** [comment]
I'm reopening this issue as I may have been incorrect with my last statement. I'm having some problem using the nodemon package to restart the server. Let it be noted that I am using sockets. Think I read somewhere that there are issues with this scenario when using sockets?? Can you confirm? Is there a workaround?

**Comment by karneaud** [comment]
turns out this issue was caused more so by `nodemon`.....using another library resolved the issue

**Comment by shamsheer7** [comment]
Try this:
1 - killall -9 node
2 - ps ax
