### ISSUE TITLE
Warning - Some middleware threw an error that was not handled properly

### ISSUE THREAD

**Issue by gary149** [franciscop/server#92]
Code to reproduce:
```js
server(
  get('/test',
    ctx => status(200).send('1'),
    ctx => status(200).send('2')
  )
)

```
I dont understand why i'm getting this warning i dont throw any error.

```
Some middleware threw an error that was not handled properly. This can happen when you do this:

~~~
// BAD:
server(ctx => { throw new Error('I am an error!'); });
~~~

To catch and handle these types of errors, add a route to the end of your middlewares to handle errors like this:

~~~
// GOOD:
const { error } = server.router;
const { status } = server.reply;

server(
  ctx => { throw new Error('I am an error!'); },
  // ...
  error(ctx => status(500).send(ctx.error.message))
);
~~~
```

**Comment by thetre97** [comment]
That is just a generic info message - It is telling how you can create a 'route' which will handle any serverjs errors. The actual error message is `Some middleware threw an error that was not handled properly.` and as you haven't created an error route, it is telling you how you can do that.

You are getting that warning as you are trying to send two replies to one request? It will fail at the second reply, as you have already sent the first one.

**Comment by franciscop** [comment]
I think showing first the actual error, and then a *furthermore, that error was not handled properly [...]* would be much better than showing the wrapping error.

**Comment by thetre97** [comment]
Something like #93 ?

**Comment by franciscop** [comment]
I have had few months to think about the whole error bit. Initially I took inspiration from React, where errors are normally clear and on-point. However, in server.js many of the errors are just extra verbose without adding much value (I know because people keep opening these kind of issues), like this issue.

Instead, the error that OP got should have been something like this:

```text
ERROR: MULTIPLE_REPLIES. The route that handles the POST request to "/test" has tried to
reply more than once. Make sure that it replies only once even with many handlers:
~~~
server(
  post('/test',
    ctx => { /* Do some work but do NOT return anything */ },
    ctx => { /* I also don't return anything :D */ },
    ctx => status(200).send('Hello world')   // Return the actual reply
);
~~~
[more info] https://serverjs.io/documentation/errors#multiple_replies


ERROR: UNHANDLED. The error "MULTIPLE_REPLIES" shown above ↑ was not handled
by your code. Please try to manage these kind of errors by adding a error route in the end
of your middleware:
~~~
const { error } = server.router;
const { status } = server.reply;
server(
  ctx => { throw new Error('I am an error!'); },
  // ...
  error(ctx => status(500).send(ctx.error.message))
);
~~~
[more info] https://serverjs.io/documentation/errors#unhandled_error
```
